from __future__ import annotations

from abc import ABC, abstractmethod

import httpx

from app.core.config import Settings


class ModelProviderUnavailableError(Exception):
    """Raised when model provider is not configured."""


class ModelProviderError(Exception):
    """Raised when model provider request fails."""


class BaseLLMProvider(ABC):
    @abstractmethod
    def generate_json(self, *, system_prompt: str, user_prompt: str) -> str:
        """Return a JSON string generated by the model."""


class UnconfiguredLLMProvider(BaseLLMProvider):
    def generate_json(self, *, system_prompt: str, user_prompt: str) -> str:
        _ = system_prompt
        _ = user_prompt
        raise ModelProviderUnavailableError("Model provider is not configured.")


class OpenAIChatProvider(BaseLLMProvider):
    def __init__(
        self,
        *,
        api_key: str,
        model: str,
        timeout_seconds: float = 30.0,
    ) -> None:
        self.api_key = api_key
        self.model = model
        self.timeout_seconds = timeout_seconds

    def generate_json(self, *, system_prompt: str, user_prompt: str) -> str:
        payload = {
            "model": self.model,
            "temperature": 0,
            "response_format": {"type": "json_object"},
            "messages": [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt},
            ],
        }

        try:
            response = httpx.post(
                "https://api.openai.com/v1/chat/completions",
                headers={
                    "Authorization": f"Bearer {self.api_key}",
                    "Content-Type": "application/json",
                },
                json=payload,
                timeout=self.timeout_seconds,
            )
            response.raise_for_status()
        except httpx.HTTPError as exc:
            raise ModelProviderError(f"OpenAI chat request failed: {exc}") from exc

        body = response.json()
        choices = body.get("choices")
        if not isinstance(choices, list) or not choices:
            raise ModelProviderError("Model response is missing choices.")

        message = choices[0].get("message")
        if not isinstance(message, dict):
            raise ModelProviderError("Model response format is invalid.")

        content = message.get("content")
        if not isinstance(content, str) or not content.strip():
            raise ModelProviderError("Model response content is empty.")
        return content


def build_llm_provider(settings: Settings) -> BaseLLMProvider:
    provider_name = settings.provider_name.lower().strip()
    if provider_name != "openai":
        return UnconfiguredLLMProvider()
    if not settings.openai_api_key:
        return UnconfiguredLLMProvider()
    return OpenAIChatProvider(api_key=settings.openai_api_key, model=settings.llm_model)

